# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore .NET tools
      run: dotnet tool restore

    - name: Restore the latest VRCSDK
      run:  bash scripts/restore_vpm_packages.sh

    - name: Run extractor
      run: |
        dotnet build extractor/extractor.fsproj
        dotnet run --project extractor/extractor.fsproj

    - name: Upload the output
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: udonInfo
        # A file, directory or wildcard pattern that describes what to upload
        path: udonInfo.json
