# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Restore Unity project
      uses: actions/cache/restore@v3
      with:
        path: project/Library
        key: unity-project

    - name: Write Unity license to file
      run: echo $DEV_ENV_FILE >> Unity.ulf
      shell: bash
      env:
        UNITY_LICENSE_FILE : ${{ secrets.UNITY_LICENSE }}

    - name: Enter the devcontainer and perform build
      uses: devcontainers/ci@v0.3
      with:
        runCmd: bash scripts/ci.sh

    - name: Save Unity project
      uses: actions/cache/save@v3
      with:
        path: project/Library
        key: unity-project

    - name: Upload the output
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: udon_info
        # A file, directory or wildcard pattern that describes what to upload
        path: udon_info.json
