# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn config get cacheFolder)" >>"$GITHUB_OUTPUT"

    - name: Retrieve yarn cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('webapp/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Restore .NET packages and tools
      run: |
        dotnet restore
        dotnet tool restore

    - name: Restore the latest VRCSDK
      run:  bash scripts/restore_vpm_packages.sh

    - name: Run extractor
      run: |
        dotnet build extractor/extractor.fsproj
        dotnet run --project extractor/extractor.fsproj

    - name: Copy udonInfo.json.gz
      uses: canastro/copy-file-action@master
      with:
        source: "./udonInfo.json.gz"
        target: "./webapp/static/assets/udonInfo.json.gz"

    - name: Build webapp
      working-directory: ./webapp
      run: |
        yarn install
        dotnet fable src --run webpack --mode production

    - name: Push artifact to gh-pages
      if: success() && github.event_name == 'push'
      uses: crazy-max/ghaction-github-pages@v2.4.1
      with:
        build_dir: webapp/output
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
