# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore .NET packages and tools
      run: |
        dotnet restore
        dotnet tool restore

    - name: Restore the latest VRCSDK
      run:  bash scripts/restore_vpm_packages.sh

    - name: Run extractor
      run: |
        dotnet build extractor/extractor.fsproj
        dotnet run --project extractor/extractor.fsproj

    - name: Build webapp
      working-directory: ./webapp
      run: |
        yarn install
        dotnet fable src && yarn webpack --mode production

    - name: Push artifact to gh-pages
      if: success() && github.event_name == 'push'
      uses: crazy-max/ghaction-github-pages@v2.4.1
      with:
        build_dir: webapp/output
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
